"""update interview model

Revision ID: ca2912efe169
Revises: 7b7bc16d3cd6
Create Date: 2025-08-02 14:32:18.282203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca2912efe169'
down_revision = '7b7bc16d3cd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('youtube_url',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('youtube_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview', schema=None) as batch_op:
        batch_op.alter_column('youtube_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('youtube_url',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
